# ugly hack to get bash working
language: c
before_install:
  - wget https://github.com/sstephenson/bats/archive/v0.3.1.tar.gz -O /tmp/bats.tar.gz
  - tar -xvf /tmp/bats.tar.gz
  - export PATH=$PATH:$PWD/bats-0.3.1/bin/
  - bash --version
script: bats test
